project:
  type: website
  output-dir: docs

website:
  title: "Karim Naguib"
  google-analytics: "G-SQNTJM494V"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: https://www.github.com/karimn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



